# Run docker-compose up
# Live long and prosper
version: "2"
services:
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:management
    environment:
        - RABBITMQ_DEFAULT_USER=guest
        - RABBITMQ_DEFAULT_PASS=guest
    ports:
        - "5672:5672"
        - "15672:15672"

  nginx:
    container_name: nginx
    restart: always
    image: nginx
    volumes:
      - ./nginx/minimal-site.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    
  astro:
    container_name: astro
    depends_on:
      - "rabbitmq"
      - "nginx"
    restart: always
    volumes:
      - ./:/app
    image: astro
    ports:
      - "3000:3000"
    environment:
      - SKF_LABS_DOMAIN=http://localhost
      - SKF_LABS_DEPLOY_MODE=port
      - PUBLIC_SUPABASE_API_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNjc2dmb29hbmtja2ZxcG1jZnliIiwicm9sZSI6ImFub24iLCJpYXQiOjE2NjkwNTYzNDcsImV4cCI6MTk4NDYzMjM0N30.aicU94g4B2IThg69VEhScf37hqJTzOc-FXMvTEX-br4
      - RUN_COMMAND="pnpm dev --host"
    labels:
      kompose.service.type: LoadBalancer
    
  workers:
    container_name: workers
    depends_on:
      - "rabbitmq"
    restart: always
    volumes:
      - ./:/app
    image: workers
    environment:
      - SKF_LABS_DOMAIN=http://localhost
      - SKF_LABS_DEPLOY_MODE=port
      - RUN_COMMAND="deno task kubernetes"
    