# Run docker-compose up
# Live long and prosper
version: "2"
services:
  rabbitmq:
    container_name: skf-rabbitmq
    image: rabbitmq:management
    environment:
        - RABBITMQ_DEFAULT_USER=guest
        - RABBITMQ_DEFAULT_PASS=guest
    ports:
        - "5672:5672"
        - "15672:15672"

  nginx:
    container_name: skf-nginx
    restart: always
    image: nginx
    volumes:
      - ./nginx/minimal-site.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    
  astro:
    container_name: skf-astro
    depends_on:
      - "rabbitmq"
      - "nginx"
    restart: always
    volumes:
      - ./:/app
    image: astro
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    ports:
      - "3000:3000"
    environment:
      - FRONTEND_URI=http://localhost
      - AUTH_METHOD=skiploginprovider
      - SKF_FLASK_DEBUG=False
      - SKF_API_URL=skf-api://api
      - SKF_JWT_SECRET=please_change_this_value_to_be_random
      - SKF_LABS_DOMAIN=http://localhost
      - SKF_LABS_DEPLOY_MODE=port
      - RABBIT_MQ_CONN_STRING=rabbitmq
      - PUBLIC_SUPABASE_API_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNjc2dmb29hbmtja2ZxcG1jZnliIiwicm9sZSI6ImFub24iLCJpYXQiOjE2NjkwNTYzNDcsImV4cCI6MTk4NDYzMjM0N30.aicU94g4B2IThg69VEhScf37hqJTzOc-FXMvTEX-br4
    command: 
      - pnpm --filter=astro dev
