---
apiVersion: v1
kind: Service
metadata:
  name: astro
  labels:
    app.kubernetes.io/name: astro
    app.kubernetes.io/instance: astro
    app.kubernetes.io/version: "0.0.1"
spec:
  type: NodePort
  ports:
    - port: 3000
      name: astro-port
  selector:
    app.kubernetes.io/name: astro
    app.kubernetes.io/instance: astro
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: astro
  labels:
    app.kubernetes.io/name: astro
    app.kubernetes.io/instance: astro
    app.kubernetes.io/version: "0.0.1"
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: astro
      app.kubernetes.io/instance: astro
  template:
    metadata:
      labels:
        app.kubernetes.io/name: astro
        app.kubernetes.io/instance: astro
    spec:
      securityContext:
        runAsUser: 100
      containers:
        - name: astro
          image: "blabla1337/skf-angular:4.1.0"
          imagePullPolicy: Always
          ports:
          - containerPort: 3000
          env:
          -  name: SKF_LABS_DOMAIN
             valueFrom:
               configMapKeyRef:
                 name: astro
                 key: SKF_LABS_DOMAIN
          -  name: SKF_LABS_DEPLOY_MODE
             valueFrom:
               configMapKeyRef:
                 name: astro
                 key: SKF_LABS_DEPLOY_MODE
          -  name: PUBLIC_SUPABASE_API_KEY
             valueFrom:
               configMapKeyRef:
                 name: astro
                 key: PUBLIC_SUPABASE_API_KEY
        

        # astro:
        #   container_name: astro
        #   depends_on:
        #     - "rabbitmq"
        #     - "nginx"
        #   restart: always
        #   volumes:
        #     - ./:/app
        #   image: astro
        #   build:
        #     context: .
        #     dockerfile: Dockerfile
        #     target: dev
        #   ports:
        #     - "3000:3000"
        #   environment:
        #     - SKF_LABS_DOMAIN=http://localhost
        #     - SKF_LABS_DEPLOY_MODE=port
        #     - PUBLIC_SUPABASE_API_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNjc2dmb29hbmtja2ZxcG1jZnliIiwicm9sZSI6ImFub24iLCJpYXQiOjE2NjkwNTYzNDcsImV4cCI6MTk4NDYzMjM0N30.aicU94g4B2IThg69VEhScf37hqJTzOc-FXMvTEX-br4
        #   command: 
        #     - pnpm --filter=astro dev --host
---
